### ISSUE TITLE
First point often contains unexpected values

### ISSUE THREAD

**Issue by cspencerjones** [cspencerjones/xlayers#7]
As pointed out by @roxyboy , the first point in the vertical direction of the new matrix often contains unexpected values. This is easily solved by excluding it, but it would be nice to identify why this happens and whether we can fix it.

**Comment by roxyboy** [comment]
I've been more or less able to mitigate this problem by having the input for `thetalayers` encompass the entire range of values it takes in the model outputs. Also as a side note, instead of calculating `zeta` as a cumulative sum of `dzeta`s, I found it better to interpolate `Z` directly onto `thetalayers`.

**Comment by cspencerjones** [comment]
This should just give a warning if there are values outside `thetalayers` I guess.

**Comment by cspencerjones** [comment]
And it actually doesn't make sense for the output matrix to be the same size as thetalayers. Since the output is actually the weighted quantity within each layer, the length of the output should be one less than thetalayers. This seems to be achieved by padding with zeros for the final level at the moment.

**Comment by cspencerjones** [comment]
xlayers is no longer under active development, so I am closing this issue.
